/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package chatter.server;

import java.io.IOException;

public class App {

    public static void main(String[] args) {
        try {
            Server.runServer(3003);
        }
        catch (IOException ex) {
           ex.printStackTrace();
        }
    }
}
